services:
    dualhand.dumper.properties_in_admin.twig.extension:
        class: DualHand\DumperBundle\Extensions\Twig\PropertiesInAdminExtension
        calls:
            - [setPool, [@sonata.admin.pool]]
            - [setRequest, [@request_stack]]
        tags:
               - { name: twig.extension }
