services:
    dualhand.dumper.properties_in_admin.twig.extension:
        class: DualHand\DumperBundle\Extensions\Twig\PropertiesInAdminExtension
        arguments: [@dualhand.dumper.manager]
        tags:
               - { name: twig.extension }
    dualhand.dumper.manager:
        class: DualHand\DumperBundle\Manager\DumperManager
        arguments: [@sonata.admin.pool, @request_stack]
